# Generated by Django 5.2.7 on 2025-10-17 19:20

import django.core.validators
import django.db.models.deletion
import fingerprint_pred.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=50, unique=True)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-training_date'],
            },
        ),
        migrations.CreateModel(
            name='FingerprintRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_image', models.ImageField(upload_to=fingerprint_pred.models.fingerprint_upload_path)),
                ('fingerprint_type', models.CharField(blank=True, choices=[('Loop', 'Loop'), ('Whorl', 'Whorl'), ('Arch', 'Arch')], max_length=10, null=True)),
                ('ridge_count', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('bmi', models.FloatField(help_text='Body Mass Index', validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(50.0)])),
                ('blood_pressure_systolic', models.IntegerField(validators=[django.core.validators.MinValueValidator(70), django.core.validators.MaxValueValidator(250)])),
                ('blood_pressure_diastolic', models.IntegerField(validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(150)])),
                ('family_history', models.BooleanField(default=False, help_text='Family history of diabetes')),
                ('predicted_risk', models.CharField(blank=True, choices=[('Low', 'Low Risk'), ('Medium', 'Medium Risk'), ('High', 'High Risk')], max_length=10, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fingerprint Record',
                'verbose_name_plural': 'Fingerprint Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
